server:
  ssl:
    key-store: classpath:keystore/chachkies.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: chachkies
    key-password: password
    enabled: true
  port: 8443

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: 42aad01b-414e-4a80-8e6d-7b9332b3aebe
            clientName: Keycloak
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: https://idp.int.identitysandbox.gov/openid_connect/authorize
            token-uri: https://idp.int.identitysandbox.gov/api/openid_connect/token
            user-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo
            jwk-set-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs
            user-name-attribute: preferred_username


