server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          chachkies-client-oidc:
            provider: spring
            client-id: chachkies-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: chachkies-client-oidc
          chachkies-client-authorization-code:
            provider: spring
            client-id: chachkies-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: chachkies.read,chachkies.write
            client-name: chachkies-client-authorization-code
          chachkies-client-client-credentials:
            provider: spring
            client-id: chachkies-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: chachkies.read,chachkies.write
            client-name: chachkies-client-client-credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000

chachkies:
  base-uri: http://127.0.0.1:8090/api/chachkies
